# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccbe5ebf73dbe8cdcb60e4680da9e8030b5407a172434efc4e6db4116a359bd30bcac23b4696ce8a2e96ef0e995d2fc69b3655cb3401aafa49dd37bf2f690dc

test:
  secret_key_base: 7e5cc0d260109682280a1aed5f0824276bca2932ac2dca4a0f8c4c702e050bd8fb834bc60ca7e598111a8e2701264e203d6d265ca939f9a50ba77f82938b7385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
